mod model;
mod probe;
mod render;
mod runner;

use std::path::Path;

use crate::{backends::BackendKind, config::MonitorConfig};

pub use model::{
    BackendStatus, BackendStatusKind, BacklightDeviceDiscovery, DdcMonitorDiscovery,
    DiscoveryBackends, DiscoveryReport, DiscoverySummary, PhysicalIdentityStatus, TargetDescriptor,
    TargetKind,
};

#[cfg(target_os = "linux")]
use runner::RealProcessRunner;

#[cfg(target_os = "linux")]
const SYSFS_BACKLIGHT_ROOT: &str = "/sys/class/backlight";

#[must_use]
pub fn discover() -> DiscoveryReport {
    #[cfg(target_os = "linux")]
    {
        discover_with_runner(&RealProcessRunner, Path::new(SYSFS_BACKLIGHT_ROOT))
    }
    #[cfg(target_os = "windows")]
    {
        windows_discover_report()
    }
    #[cfg(not(any(target_os = "linux", target_os = "windows")))]
    {
        model::windows_discovery_deferred_report()
    }
}

#[cfg(target_os = "windows")]
fn generate_candidate_windows_config(
    monitors: &[crate::platform::windows::topology::WindowsMonitorObservation],
) -> String {
    use std::fmt::Write;
    let mut snippet = String::from(
        "# Candidate Windows monitor configuration generated by sunreactorctl discover\n",
    );
    let mut candidate_count = 0;
    for mon in monitors {
        match mon.identity_quality {
            crate::platform::windows::topology::IdentityQuality::Strong => {
                if let Some(ref id) = mon.canonical_id {
                    let label = mon.name.as_deref().unwrap_or("Display");
                    let _ = writeln!(
                        snippet,
                        "\n# [[monitors]]\n# id = \"{id}\"\n# name = \"{label}\"\n# min_brightness = 10\n# max_brightness = 100"
                    );
                    candidate_count += 1;
                }
            }
            crate::platform::windows::topology::IdentityQuality::StableDevice => {
                if let Some(ref id) = mon.canonical_id {
                    let label = mon.name.as_deref().unwrap_or("Display");
                    let _ = writeln!(
                        snippet,
                        "\n# Qualified device-bound candidate (port independence unverified):\n# [[monitors]]\n# id = \"{id}\"\n# name = \"{label}\"\n# min_brightness = 10\n# max_brightness = 100"
                    );
                    candidate_count += 1;
                }
            }
            _ => {}
        }
    }
    if candidate_count == 0 {
        snippet.push_str(
            "\n# No monitors with Strong or StableDevice identity detected.\n# Ineligible monitors (PortBound, Ambiguous, Virtual, Unknown) are excluded from candidate config.\n",
        );
    }
    snippet
}

#[cfg(target_os = "windows")]
#[allow(clippy::too_many_lines)]
#[must_use]
pub fn windows_discover_report() -> DiscoveryReport {
    use crate::platform::windows::display::WindowsDisplayKind;
    use crate::platform::windows::topology::{capture_topology_snapshot, IdentityQuality};

    let snapshot = match capture_topology_snapshot() {
        Ok(s) => s,
        Err(e) => {
            return DiscoveryReport {
                summary: DiscoverySummary {
                    ddc_monitors: 0,
                    backlight_devices: 0,
                    viable_targets: 0,
                },
                backends: DiscoveryBackends {
                    ddcutil: BackendStatus {
                        backend: String::from("DXVA2 / DDC"),
                        available: false,
                        status: BackendStatusKind::Error,
                        message: format!("Topology query failed: {e}"),
                        guidance: None,
                    },
                    brightnessctl: BackendStatus {
                        backend: String::from("WMI / WinRT"),
                        available: false,
                        status: BackendStatusKind::Unavailable,
                        message: String::from("Internal panel brightness deferred to W3"),
                        guidance: None,
                    },
                    sysfs: BackendStatus {
                        backend: String::from("CCD / SetupAPI"),
                        available: false,
                        status: BackendStatusKind::Error,
                        message: format!("CCD failure: {e}"),
                        guidance: None,
                    },
                },
                ddc_monitors: Vec::new(),
                backlight_devices: Vec::new(),
                ddc_observation_complete: false,
                windows_displays: Vec::new(),
                notes: vec![format!("Error discovering Windows display topology: {e}")],
                config_snippet: String::new(),
            };
        }
    };

    let mut ddc_monitors = Vec::new();
    let mut backlight_devices = Vec::new();
    let mut windows_displays = Vec::new();

    for mon in &snapshot.monitors {
        let quality_str = mon.identity_quality.to_string();
        let kind_str = mon.kind.to_string();
        let rect_str = mon
            .desktop_rect
            .map(|(l, t, r, b)| format!("{}x{} @ {},{}", r - l, b - t, l, t));

        let (brightness_capable, native_min, native_current, native_max, normalized_pct, cap_note) =
            if mon.kind == WindowsDisplayKind::ExternalMonitor {
                if let Some(ref cid) = mon.canonical_id {
                    let cap =
                        crate::platform::windows::brightness::probe_external_capability_with_api(
                            &crate::platform::windows::brightness::Win32MonitorConfigApi,
                            cid,
                        );
                    match cap {
                        crate::platform::windows::brightness::ExternalBrightnessCapability::Supported {
                            range,
                            normalized_current_pct,
                        } => (
                            Some(true),
                            Some(range.min),
                            Some(range.current),
                            Some(range.max),
                            Some(normalized_current_pct),
                            Some(String::from("DXVA2 High-Level API / Unique physical mapping")),
                        ),
                        crate::platform::windows::brightness::ExternalBrightnessCapability::Unsupported {
                            reason,
                        } => (Some(false), None, None, None, None, Some(reason)),
                        crate::platform::windows::brightness::ExternalBrightnessCapability::TemporarilyUnavailable {
                            reason,
                        } => (Some(false), None, None, None, None, Some(reason)),
                        crate::platform::windows::brightness::ExternalBrightnessCapability::InvalidRange {
                            min,
                            current,
                            max,
                        } => (
                            Some(false),
                            Some(min),
                            Some(current),
                            Some(max),
                            None,
                            Some(String::from("Invalid native brightness range")),
                        ),
                        crate::platform::windows::brightness::ExternalBrightnessCapability::AmbiguousPhysicalMapping {
                            count,
                        } => (
                            Some(false),
                            None,
                            None,
                            None,
                            None,
                            Some(format!("Ambiguous physical mapping: {count} handles")),
                        ),
                        crate::platform::windows::brightness::ExternalBrightnessCapability::IdentityNotMutationEligible {
                            quality,
                        } => (
                            Some(false),
                            None,
                            None,
                            None,
                            None,
                            Some(format!("Identity not mutation eligible ({quality})")),
                        ),
                        crate::platform::windows::brightness::ExternalBrightnessCapability::TopologyUnavailable => {
                            (Some(false), None, None, None, None, Some(String::from("Topology unavailable")))
                        }
                        crate::platform::windows::brightness::ExternalBrightnessCapability::NativeApiFailure {
                            operation,
                            code,
                        } => (
                            Some(false),
                            None,
                            None,
                            None,
                            None,
                            Some(format!("{operation} failed with Win32 error {code}")),
                        ),
                    }
                } else {
                    (
                        Some(false),
                        None,
                        None,
                        None,
                        None,
                        Some(String::from("No canonical ID")),
                    )
                }
            } else if mon.kind == WindowsDisplayKind::InternalPanel {
                (
                    Some(false),
                    None,
                    None,
                    None,
                    None,
                    Some(String::from("Internal panel brightness deferred to W3B")),
                )
            } else {
                (
                    Some(false),
                    None,
                    None,
                    None,
                    None,
                    Some(format!("{} display (DDC unsupported)", mon.kind)),
                )
            };

        windows_displays.push(model::WindowsDisplayDiscovery {
            display_number: mon.display_number,
            canonical_id: mon.canonical_id.clone(),
            display_label: mon.display_label.clone(),
            stable_id: mon.canonical_id.clone(),
            identity_quality: quality_str,
            mutation_eligibility: mon.mutation_eligibility.to_string(),
            name: mon.name.clone(),
            kind: kind_str,
            active: mon.active,
            target_available: mon.target_available,
            is_primary: mon.is_primary,
            output_technology: mon.output_technology.clone(),
            gdi_device_name: mon.gdi_device_name.clone(),
            adapter_luid: format!("{:x}_{:x}", mon.adapter_luid.0, mon.adapter_luid.1),
            source_id: mon.source_id,
            target_id: mon.target_id,
            connector_instance: mon.connector_instance,
            container_id: mon.container_id.clone(),
            device_instance_id: mon.device_instance_id.clone(),
            hardware_ids: mon.hardware_ids.clone(),
            edid_manufacturer: mon.edid_manufacturer.clone(),
            edid_product_code: mon.edid_product_code,
            physical_monitors_count: mon.physical_monitors_count,
            physical_monitor_description: mon.physical_monitor_description.clone(),
            desktop_rect: rect_str,
            note: mon.note.clone(),
            brightness_capable,
            native_min,
            native_current,
            native_max,
            normalized_current_percent: normalized_pct,
            capability_note: cap_note.clone(),
        });

        if mon.kind == WindowsDisplayKind::ExternalMonitor {
            let id_status = match mon.identity_quality {
                IdentityQuality::Strong | IdentityQuality::StableDevice => {
                    PhysicalIdentityStatus::Unique
                }
                IdentityQuality::Ambiguous => PhysicalIdentityStatus::Ambiguous,
                IdentityQuality::PortBound => PhysicalIdentityStatus::TopologyBound,
                _ => PhysicalIdentityStatus::Insufficient,
            };
            ddc_monitors.push(DdcMonitorDiscovery {
                occurrence_id: format!("win-disp-{}", mon.display_number),
                stable_id: mon
                    .stable_id
                    .clone()
                    .unwrap_or_else(|| format!("win-disp-{}", mon.display_number)),
                identity_status: id_status,
                manufacturer: mon.edid_manufacturer.clone(),
                model: mon.name.clone(),
                serial: mon.container_id.clone(),
                display_number: mon.display_number,
                bus_number: None,
                connector: Some(mon.output_technology.clone()),
                brightness_vcp_supported: brightness_capable,
                backend_viable: brightness_capable.unwrap_or(false)
                    && mon.active
                    && mon.target_available,
                note: cap_note.or_else(|| mon.note.clone()),
            });
        } else if mon.kind == WindowsDisplayKind::InternalPanel {
            backlight_devices.push(BacklightDeviceDiscovery {
                stable_id: mon
                    .stable_id
                    .clone()
                    .unwrap_or_else(|| format!("win-panel-{}", mon.display_number)),
                device_name: mon
                    .name
                    .clone()
                    .unwrap_or_else(|| format!("Internal Panel {}", mon.display_number)),
                class: String::from("internal_panel"),
                max_brightness: None,
                backlight_type: Some(String::from("eDP")),
                probe_source: String::from("CCD"),
                sysfs_path: mon.gdi_device_name.clone().unwrap_or_default(),
                ddcci_connector: Some(mon.output_technology.clone()),
                backend_viable: mon.active && mon.target_available,
                note: mon.note.clone(),
            });
        }
    }

    let summary = DiscoverySummary {
        ddc_monitors: ddc_monitors.len(),
        backlight_devices: backlight_devices.len(),
        viable_targets: ddc_monitors.iter().filter(|m| m.backend_viable).count()
            + backlight_devices
                .iter()
                .filter(|b| b.backend_viable)
                .count(),
    };

    let backends = DiscoveryBackends {
        ddcutil: BackendStatus {
            backend: String::from("DXVA2 / DDC"),
            available: true,
            status: BackendStatusKind::Ok,
            message: String::from(
                "Native Windows physical monitor enumeration active (mutation deferred to W3)",
            ),
            guidance: None,
        },
        brightnessctl: BackendStatus {
            backend: String::from("WMI / WinRT"),
            available: false,
            status: BackendStatusKind::Unavailable,
            message: String::from("Internal backlight control deferred to W3"),
            guidance: None,
        },
        sysfs: BackendStatus {
            backend: String::from("CCD / SetupAPI"),
            available: true,
            status: BackendStatusKind::Ok,
            message: String::from("Native Windows CCD display topology & PnP devnodes active"),
            guidance: None,
        },
    };

    let mut notes = snapshot.notes;
    notes.push(String::from(
        "SunReactor Windows W2: Read-only display topology & stable identity qualification active.",
    ));

    let config_snippet = generate_candidate_windows_config(&snapshot.monitors);

    DiscoveryReport {
        summary,
        backends,
        ddc_observation_complete: true,
        ddc_monitors,
        backlight_devices,
        windows_displays,
        notes,
        config_snippet,
    }
}

#[must_use]
pub fn discover_targets() -> Vec<TargetDescriptor> {
    discover().viable_targets()
}

impl DiscoveryReport {
    #[must_use]
    pub fn render_human(&self) -> String {
        render::render_human(self)
    }

    #[must_use]
    pub fn render_json(&self) -> String {
        render::render_json(self)
    }

    #[must_use]
    pub fn viable_targets(&self) -> Vec<TargetDescriptor> {
        let mut targets = Vec::new();

        for monitor in &self.ddc_monitors {
            if monitor.backend_viable {
                targets.push(TargetDescriptor {
                    id: monitor.occurrence_id.clone(),
                    label: monitor.target_label(),
                    kind: TargetKind::ExternalMonitor,
                    backend: BackendKind::Ddc,
                });
            }
        }

        for device in &self.backlight_devices {
            if device.backend_viable && !is_ddcci_alias_of_viable_ddc(device, &self.ddc_monitors) {
                targets.push(TargetDescriptor {
                    id: device.stable_id.clone(),
                    label: device.device_name.clone(),
                    kind: TargetKind::InternalPanel,
                    backend: BackendKind::Backlight,
                });
            }
        }

        targets
    }

    /// Candidates that can be added without enabling a bus-only selector or
    /// accepting an ambiguous DDC match. This is intentionally the same
    /// safety gate used by the generated config snippet.
    #[must_use]
    pub(crate) fn importable_monitor_configs(&self) -> Vec<MonitorConfig> {
        render::importable_monitor_configs(self)
    }

    /// `None` means ddcutil could not complete a VCP capability probe. A
    /// caller may retry that transient observation, but must not treat it as
    /// proof that the display lacks brightness support.
    #[must_use]
    pub(crate) fn has_incomplete_ddc_probe(&self) -> bool {
        !self.ddc_observation_complete
            || self
                .ddc_monitors
                .iter()
                .any(|monitor| monitor.brightness_vcp_supported.is_none())
    }
}

/// Returns true when a backlight device is topology-aliased to the same
/// physical monitor as at least one *viable* DDC monitor.
///
/// This is the only cross-backend duplication signal SunReactor accepts.
/// It requires explicit evidence: `ddcci_connector` (the proven kernel/driver
/// `ddcci_backlight` symlink convergence) must match a DDC monitor's DRM
/// connector. Names, ordering, and backlight type are never evidence.
pub(crate) fn is_ddcci_alias_of_viable_ddc(
    backlight: &BacklightDeviceDiscovery,
    ddc_monitors: &[DdcMonitorDiscovery],
) -> bool {
    let Some(connector) = backlight.ddcci_connector.as_deref() else {
        return false;
    };
    ddc_monitors
        .iter()
        .any(|monitor| monitor.backend_viable && monitor.connector.as_deref() == Some(connector))
}

pub(crate) fn assign_ddc_occurrence_ids(monitors: &mut [DdcMonitorDiscovery]) {
    let selectors = monitors.iter().map(discovery_selector).collect::<Vec<_>>();

    for (index, monitor) in monitors.iter_mut().enumerate() {
        let topology = monitor
            .bus_number
            .map(|bus| format!("bus-{bus}"))
            .or_else(|| monitor.connector.as_deref().map(model::slugify))
            .unwrap_or_else(|| format!("display-{index}"));
        monitor.occurrence_id = format!("ddc-occurrence:{topology}:record-{index}");

        let ambiguous = selectors.iter().enumerate().any(|(other_index, other)| {
            other_index != index
                && crate::backends::ddc::selector_relation(&selectors[index], other)
                    != Ok(crate::backends::ddc::DdcSelectorRelation::ProvablyDisjoint)
        });

        monitor.identity_status = if ambiguous {
            PhysicalIdentityStatus::Ambiguous
        } else if monitor.serial.is_some() || monitor.model.is_some() {
            PhysicalIdentityStatus::Unique
        } else if monitor.bus_number.is_some() || monitor.connector.is_some() {
            PhysicalIdentityStatus::TopologyBound
        } else {
            PhysicalIdentityStatus::Insufficient
        };
    }
}

fn discovery_selector(monitor: &DdcMonitorDiscovery) -> crate::config::MonitorSelector {
    crate::config::MonitorSelector {
        connector: monitor.connector.clone(),
        serial: monitor.serial.clone(),
        model: monitor.model.clone(),
        edid: None,
        sysfs_path: None,
        ddc_bus: if monitor.serial.is_none() && monitor.model.is_none() {
            monitor.bus_number.map(|bus| bus as u8)
        } else {
            None
        },
        ddc_address: None,
    }
}

pub(crate) fn discover_with_runner<R: runner::ProcessRunner>(
    runner: &R,
    sysfs_root: &Path,
) -> DiscoveryReport {
    let snapshot = probe::discover_with_runner(runner, sysfs_root);
    render::build_report(snapshot)
}

#[cfg(test)]
pub(crate) fn discover_with_roots<R: runner::ProcessRunner>(
    runner: &R,
    sysfs_root: &Path,
    drm_root: &Path,
) -> DiscoveryReport {
    let snapshot = probe::discover_with_roots(runner, sysfs_root, drm_root);
    render::build_report(snapshot)
}

#[cfg(test)]
pub(crate) use runner::{CommandError, CommandOutput, ProcessRunner};

#[cfg(test)]
mod tests;
